const ProjectsInfo = [
    {
        name: 'Virtual Flashcards',
        description: 'A web app that helps the user create, edit, review and orgaznize virtual flashcards.',
        demo: 'https://virtual-flashcards.herokuapp.com/',
        gitHub: 'https://github.com/debelopumento/flashcards',
        techUsed: [
            'HTML, ',
            'CSS, ',
            'Javascript, ',
            'React Router, ',
            'React, ',
            'Redux, ',
            'NodeJs',
        ],
        thumbnail: 'https://github.com/debelopumento/portfolio/blob/master/public/images/thumb_flashcards.png?raw=true',
    },

    {
        name: 'Is It Hotter Than Today In History',
        description: 'This web app shows the user if it is currently hotter than the same day in the selected year in history.',
        demo: 'https://is-it-getting-hotter.herokuapp.com',
        gitHub: 'https://github.com/debelopumento/weather-chart',
        techUsed: [
            'HTML, ',
            'CSS, ',
            'Javascript, ',
            'React, ',
            'Redux, ',
            'D3',
        ],
        thumbnail: 'https://github.com/debelopumento/portfolio/blob/master/public/images/thumb_weatherChart.png?raw=true',
    },
    {
        name: 'Tobu',
        description: 'A Voice Control Runner Game for Google Chrome, with Web Speech Recognition API.',
        demo: 'https://cryptic-atoll-29351.herokuapp.com/',
        gitHub: 'https://github.com/debelopumento/phaser-test',
        techUsed: [
            'HTML, ',
            'CSS, ',
            'Javascript, ',
            'Phaser, ',
            'React, ',
            'Redux, ',
            'NodeJs',
        ],
        thumbnail: 'https://github.com/debelopumento/portfolio/blob/master/public/images/thumb_phaserTest.png?raw=true',
    },
    {
        name: 'Bill Split App',
        description: 'If the user frequently shares expenses with someone, like a roommate, this app keeps a running total of who owes who what amount.',
        demo: 'https://bill-split-app.herokuapp.com/',
        gitHub: 'https://github.com/debelopumento/billsplit-app',
        techUsed: [
            'HTML, ',
            'CSS, ',
            'Javascript, ',
            'JQuery, ',
            'NodeJs, ',
            'Express, ',
            'Mocha, ',
            'Chai',
        ],
        thumbnail: 'https://github.com/debelopumento/portfolio/blob/master/public/images/thumb_billSplitApp.png?raw=true',
    },
    {
        name: 'Yelp with Google Map',
        description: 'This app helps you search for local businesses with Yelp and provides links to navigation with Google Map. It is a combination of Yelp and Goolge Map for mobile devices.',
        demo: 'https://debelopumento.github.io/Yelp-with-Google-Map/',
        gitHub: 'https://github.com/debelopumento/Yelp-with-Google-Map',
        techUsed: ['HTML, ', 'CSS, ', 'Javascript, ', 'JQuery'],
    },
];

export default ProjectsInfo;
